pipeline {
    agent {
        docker {
            image 'maven:3.8.6-jdk-11-slim'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true clean test'
            }
        }
        stage('Results') {
            steps {
                publishGherkinResults '**/*OctaneGherkinResults.xml'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Delivering ./jenkins/scripts/deliver.sh'
            }
        }
    }
}
